// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Dflxit1zneF8ALSDL4fCOor3nY_UKlk',
    appId: '1:620096473911:web:80c5b806951e81e1fb28b2',
    messagingSenderId: '620096473911',
    projectId: 'mobile-app-5e0b4',
    authDomain: 'mobile-app-5e0b4.firebaseapp.com',
    storageBucket: 'mobile-app-5e0b4.firebasestorage.app',
    measurementId: 'G-PEY47K9XQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsUrVSYQoZMsTPYITN9yBkpa0rfv6XaaU',
    appId: '1:620096473911:android:fea26cf670661b8efb28b2',
    messagingSenderId: '620096473911',
    projectId: 'mobile-app-5e0b4',
    storageBucket: 'mobile-app-5e0b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBkkpkQpM2oedHPJVDv5ZVPQTJXQqxEjo',
    appId: '1:620096473911:ios:4b2c6b5cf5938796fb28b2',
    messagingSenderId: '620096473911',
    projectId: 'mobile-app-5e0b4',
    storageBucket: 'mobile-app-5e0b4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBkkpkQpM2oedHPJVDv5ZVPQTJXQqxEjo',
    appId: '1:620096473911:ios:4b2c6b5cf5938796fb28b2',
    messagingSenderId: '620096473911',
    projectId: 'mobile-app-5e0b4',
    storageBucket: 'mobile-app-5e0b4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Dflxit1zneF8ALSDL4fCOor3nY_UKlk',
    appId: '1:620096473911:web:32f36e49b00ef099fb28b2',
    messagingSenderId: '620096473911',
    projectId: 'mobile-app-5e0b4',
    authDomain: 'mobile-app-5e0b4.firebaseapp.com',
    storageBucket: 'mobile-app-5e0b4.firebasestorage.app',
    measurementId: 'G-K42XV7YNC9',
  );

}